### ISSUE TITLE
add playtime of game while request item

### ISSUE THREAD

**Issue by webben-de** [webben-de/ASF_ItemDropper#5]

**Comment by Sniper677** [comment]
Item still drops, but command throws an error.

master:  <bot1> Unbekannter Befehl!

**Comment by webben-de** [comment]
mhh, no stack trace somewhere?

**Comment by Sniper677** [comment]
```
2020-10-06 12:13:30|ArchiSteamFarm-6348|ERROR|ASF|OnBotCommand() System.NullReferenceException: Object reference not set to an instance of an object.
   at ASFItemDropManager.ItemDropHandler.checkTime(UInt32 appid, UInt32 itemdefid, Bot bot)
   at ASFItemDropManager.ASFItemDropManager.CheckItem(UInt64 steamID, Bot bot, String appid, String itemdefId)
   at ArchiSteamFarm.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFItemDropManager.ASFItemDropManager.CheckItem(UInt64 steamID, String botNames, String appid, String itemdefId)
   at ASFItemDropManager.ASFItemDropManager.OnBotCommand(Bot bot, UInt64 steamID, String message, String[] args)
   at ArchiSteamFarm.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, UInt64 steamID, String message, String[] args)
```

**Comment by webben-de** [comment]
will this happen on both command variations? meaning with and without bots passed.

**Comment by Sniper677** [comment]
yes, for both variants the same.

**Comment by Sniper677** [comment]
no errors anymore, but a zero playtime, which cannot be.

master:	!idrop 304930 10000
master:	<bot1> Item dropped => ItemID: 304930_3234105902048897393, ItemDefinition: 58606 @ 20201006T183501Z (playtime: 0)

**Comment by webben-de** [comment]
do you have access to the console logs? There should be a json output of the  consumePlaytime request and before that a wrote a line to log the entire request.

**Comment by Sniper677** [comment]
done
